# Generated by Django 2.0 on 2017-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tendencia', models.CharField(max_length=150)),
                ('total_ocurrencias', models.IntegerField(default=None)),
            ],
        ),
    ]
