# Generated by Django 2.0 on 2017-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_tendencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesados',
            name='T_arte',
            field=models.IntegerField(default=None),
        ),
    ]
