# Generated by Django 2.0 on 2017-12-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0003_procesados_t_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesados',
            name='T_arte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_baile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_baleares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_cine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_conciertos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_formentera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_hotel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_ibiza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_mallorca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_menorca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_musica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_playa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_restaurantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='T_teatro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='anyo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='dia_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='dia_sem',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='hora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='idioma',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='isla',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='mes_nom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='mes_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='minuto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='municipio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='polaridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procesados',
            name='tipo_interaccion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tendencias',
            name='total_ocurrencias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
