# Generated by Django 2.0 on 2017-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0005_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nivel',
            new_name='level',
        ),
    ]
